apiVersion: v1
kind: Pod
metadata:
  namespace: default
  labels:
    run: busybox-security-context
  name: busybox-security-context
spec:
  containers:
  - command: ["sh", "-c"]
    args:
      - "sleep 1h"
    image: busybox:1.28
    name: busybox-security-context
    volumeMounts:
    - name: empty
      mountPath: /data/test
    securityContext:
      allowPrivilegeEscalation: false
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
    - name: empty
      emptyDir: {}
---
