apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2023-02-18T15:22:38Z"
  name: test1-role
  namespace: kube-system
  resourceVersion: "1638"
  uid: 62d48525-092e-4280-9e66-3b718a70e3a7
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
