apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  hostPath:
   path: /tmp/logs
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pv
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: logs-pv
      volumes:
        - name: logs-pv
          persistentVolumeClaim:
            claimName: logs-pv
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: custom
reclaimPolicy: Delete
volumeBindingMode: Immediate
provisioner: k8s.io/minikube-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: custom-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: "custom"