apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi
  name: multi
  namespace: default
spec:
  containers:
  - name: streaming 
    image: busybox:1.35.0 
    args: ["/bin/sh", "-c", 'tail -n+1 -f /var/log/nginx/access.log']
    volumeMounts:
    - mountPath: /var/log/nginx
      name: emptydirv
  - image: nginx:1.23.0
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
    ports:
      - containerPort: 80
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/log/nginx
      name: emptydirv
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ubuntu-testing
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: emptydirv
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: multinginx
  name: multinginx
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: www
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: stress-1
  name: stress-1
  namespace: default
spec:
  containers:
  - name: streaming 
    image: polinux/stress:1.0.4 
    args: ["/bin/sh", "-c", 'stress --vm 1 --vm-bytes $(shuf -i 20-200 -n 1)M --vm-hang 1']
    resources:
      requests:
        memory: "250Mi"
      limits:
        memory: "250Mi"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: stress-2
  name: stress-2
  namespace: default
spec:
  containers:
  - name: streaming 
    image: polinux/stress:1.0.4 
    args: ["/bin/sh", "-c", 'stress --vm 1 --vm-bytes $(shuf -i 20-200 -n 1)M --vm-hang 1']
    resources:
      requests:
        memory: "250Mi"
      limits:
        memory: "250Mi"
