apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: main
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: main-rb
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: main
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: observer
