---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: api-call
  namespace: t23
automountServiceAccountToken: false
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: api-call-token
#   namespace: t23
#   annotations:
#     kubernetes.io/service-account.name: api-call
# type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-services
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rb1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-services
subjects:
- kind: ServiceAccount
  name: api-call
  namespace: t23
